version: '3.5'
services:
    myredis:
        container_name: myweb.redis
        image: redis:6.0.5-alpine
        ports:
            - "6379:6379"
    mysql:
        image: mysql:5.7
        container_name: myweb.mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
        ports:
            - "3306:3306"
    myweb:
      container_name: myweb
      build: .
      ports:
        - "8088:5000"
      environment:
        - REDIS_HOST=myredis
        - DB_HOST=mysql
      volumes:
        - .:/app
      depends_on:
        - myredis
        - mysql
